tables:
  - usersTable

types:
  - name: User
    ref: usersTable
    fields:
      - name: username
        type: String
        required: true
      - name: email
        type: String
        required: true

